# Generated by Django 5.0 on 2024-03-11 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='room_rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_images', models.ImageField(upload_to='images/')),
                ('room_prize', models.IntegerField()),
                ('room_size', models.CharField(max_length=100)),
                ('total_rooms', models.IntegerField()),
                ('room_location', models.CharField(max_length=100)),
                ('line_bill_needed', models.BooleanField(default=False)),
                ('room_allow', models.CharField(max_length=100)),
                ('room_for', models.CharField(choices=[('B', 'Boys'), ('G', 'Girls')], max_length=1)),
                ('smoking', models.BooleanField(default=False)),
                ('drinking', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
