# Generated by Django 5.0 on 2024-03-11 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room_rent',
            name='room_images',
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='room_images/')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.room_rent')),
            ],
        ),
        migrations.AddField(
            model_name='room_rent',
            name='room_images',
            field=models.ManyToManyField(blank=True, to='app.roomimage'),
        ),
    ]
