# Generated by Django 5.0 on 2024-03-11 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_room_rent_room_images_delete_roomimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room_rent',
            name='room_desc',
            field=models.TextField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
